### ISSUE TITLE
Issue 14

### ISSUE THREAD

**Issue by abishai** [evilsocket/gibson#17] opened 2013-07-24 18:28 UTC
Issue with CPU continues for the last unstable version of gibson under FreeBSD (yes, I deleted all previous source files and cmake generated stuff).

```
root@killboard:/home/abi/gibson-unstable # gdb66 -ex "set pagination 0" -ex "thread apply all bt" --batch -p `pgrep gibson`
0x000000080090c46c in clock_gettime () from /lib/libc.so.7
root@killboard:/home/abi/gibson-unstable # gdb66 attach `pgrep gibson`
GNU gdb 6.6 [GDB v6.6 for FreeBSD]
Copyright (C) 2006 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-portbld-freebsd9.1"...
attach: No such file or directory.
Attaching to process 2981
Reading symbols from /usr/local/sbin/gibson...done.
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
0x000000080090c46c in clock_gettime () from /lib/libc.so.7
(gdb) bt
#0  0x000000080090c46c in clock_gettime () from /lib/libc.so.7
#1  0x000000000040516e in gbGetTime (seconds=0x7fffffffd3b8, milliseconds=0x7fffffffd3b0) at /home/abi/gibson-unstable/src/net.c:214
#2  0x0000000000405564 in processTimeEvents (eventLoop=0x800c70068) at /home/abi/gibson-unstable/src/net.c:337
#3  0x0000000000405886 in gbProcessEvents (eventLoop=0x800c70068, flags=3) at /home/abi/gibson-unstable/src/net.c:463
#4  0x00000000004059b2 in gbEventLoopMain (eventLoop=0x800c70068) at /home/abi/gibson-unstable/src/net.c:495
#5  0x00000000004036e7 in main (argc=1, argv=0x7fffffffdd60) at /home/abi/gibson-unstable/src/gibson.c:288
(gdb)
```

Maybe it's my bad karma... I'm scared what disaster would happen when I'll try to build cli and php extention :)

**Comment by evilsocket** [comment] 2013-07-24 19:16
duplicate of issue #14 ... will close this and reopen it.

**Closed as completed by evilsocket** 2013-07-24 19:16 UTC
Labels: duplicate
